# Generated by Django 5.1 on 2025-02-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
