# Generated by Django 5.1 on 2024-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0005_alter_package_duration_alter_package_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Front Desk', 'Front Desk'), ('Housekeeping', 'Housekeeping'), ('Culinary', 'Culinary'), ('Entertainment', 'Entertainment'), ('Maintenance', 'Maintenance'), ('Customer Service', 'Customer Service')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('start_date', models.DateField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
            ],
        ),
    ]
