# Generated by Django 5.1 on 2024-10-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
