# Generated by Django 5.1 on 2024-10-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0013_packagemanagement_delete_package'),
        ('staffs', '0006_room_price'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.PositiveIntegerField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('additional_requests', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanal.packagemanagement')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.room')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.booking')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='menu_items',
            field=models.ManyToManyField(through='userapp.MenuItemQuantity', to='staffs.menuitem'),
        ),
    ]
