# Generated by Django 5.1 on 2024-10-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0013_packagemanagement_delete_package'),
        ('staffs', '0006_room_price'),
        ('userapp', '0002_booking_menuitemquantity_booking_menu_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingManagement',
        ),
    ]
