# Generated by Django 5.1 on 2024-10-07 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0014_packagemanagement_additional_day_price'),
        ('staffs', '0006_room_price'),
        ('userapp', '0005_alter_packagebooking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='menu_items',
            field=models.ManyToManyField(related_name='bookings', through='userapp.MenuItemQuantity', to='staffs.menuitem'),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanal.packagemanagement'),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='staffs.room'),
        ),
    ]
