# Generated by Django 5.1 on 2024-10-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_packagebooking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagebooking',
            name='menu_items',
        ),
        migrations.RenameField(
            model_name='packagebooking',
            old_name='num_people',
            new_name='num_adults',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='additional_requests',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='num_rooms',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='payment_method',
            field=models.CharField(default='Credit Card', max_length=50),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='userapp.userdb'),
        ),
        migrations.DeleteModel(
            name='MenuItemQuantity',
        ),
    ]
