# Generated by Django 5.1 on 2024-10-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_bookingpackage_email_bookingpackage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
