# Generated by Django 5.1 on 2024-10-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_userdb_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagebooking',
            options={},
        ),
    ]
