# Generated by Django 5.1 on 2024-10-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_alter_packagebooking_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='emailid',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='userdb',
            constraint=models.UniqueConstraint(fields=('emailid', 'mobilenumber'), name='unique_email_phone_combination'),
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='username',
        ),
    ]
