# Generated by Django 5.1 on 2024-10-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_userdb_unique_together_alter_userdb_emailid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='emailid',
        ),
        migrations.AddField(
            model_name='userdb',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
