# Generated by Django 5.1 on 2024-10-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_remove_userdb_emailid_userdb_email_alter_userdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='email',
            new_name='emailid',
        ),
    ]
