# Generated by Django 5.1 on 2024-10-22 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_alter_userdb_emailid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdb',
            name='unique_email_phone_combination',
        ),
        migrations.AddField(
            model_name='userdb',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='emailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together={('emailid', 'username')},
        ),
    ]
