# Generated by Django 5.1 on 2024-10-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_rename_emailid_userdb_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdb',
            table='users',
        ),
    ]
