# Generated by Django 5.1 on 2024-09-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0007_staff_password_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(default='default_package_image.jpg', upload_to='package_images/'),
        ),
    ]
