# Generated by Django 5.1 on 2024-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0011_remove_package_duration_remove_package_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(default='1 Day', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='default_package_image.jpg', upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
