# Generated by Django 5.1 on 2024-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0012_remove_package_created_at_remove_package_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
