# Generated by Django 5.1 on 2024-10-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0013_packagemanagement_delete_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='additional_day_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
