# Generated by Django 5.1 on 2024-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0015_packagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='category',
            field=models.CharField(choices=[('BASIC', 'Basic Package'), ('PREMIUM', 'Premium Package'), ('FAMILY', 'Family Package'), ('CORPORATE', 'Corporate Package'), ('LUXURY', 'Luxury Package'), ('ADVENTURE', 'Adventure Package'), ('ROMANTIC', 'Romantic Getaway'), ('WELLNESS', 'Wellness Retreat'), ('GROUP', 'Group Package')], default='BASIC', max_length=20),
        ),
    ]
