# Generated by Django 5.1 on 2024-10-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0016_packagemanagement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemanagement',
            name='category',
        ),
    ]
