# Generated by Django 5.1 on 2024-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0017_remove_packagemanagement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageManagement1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('additional_day_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('category', models.CharField(choices=[('BASIC', 'Basic Package'), ('PREMIUM', 'Premium Package'), ('FAMILY', 'Family Package'), ('CORPORATE', 'Corporate Package'), ('LUXURY', 'Luxury Package'), ('ADVENTURE', 'Adventure Package'), ('ROMANTIC', 'Romantic Getaway'), ('WELLNESS', 'Wellness Retreat'), ('GROUP', 'Group Package')], default='BASIC', max_length=20)),
            ],
        ),
    ]
