# Generated by Django 5.1 on 2024-10-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0018_packagemanagement1'),
        ('staffs', '0006_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='PackageCategory',
        ),
        migrations.AddField(
            model_name='packagemanagement',
            name='menu_items',
            field=models.ManyToManyField(to='staffs.menuitem'),
        ),
        migrations.AddField(
            model_name='packagemanagement',
            name='rooms',
            field=models.ManyToManyField(to='staffs.room'),
        ),
        migrations.AddField(
            model_name='packagemanagement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanal.category'),
        ),
    ]
