# Generated by Django 5.1 on 2024-10-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0019_category_foodcategory_delete_packagecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemanagement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanal.category'),
        ),
    ]
