# Generated by Django 5.1 on 2024-10-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0020_alter_packagemanagement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemanagement',
            name='category',
        ),
    ]
