# Generated by Django 5.1 on 2024-10-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0021_remove_packagemanagement_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
