# Generated by Django 5.1 on 2024-10-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0022_delete_foodcategory'),
        ('staffs', '0007_foodcategory_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemanagement',
            name='additional_day_price',
        ),
        migrations.RemoveField(
            model_name='packagemanagement',
            name='rooms',
        ),
        migrations.AddField(
            model_name='packagemanagement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanal.category'),
        ),
        migrations.AddField(
            model_name='packagemanagement',
            name='food_categories',
            field=models.ManyToManyField(blank=True, to='staffs.foodcategory'),
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='staffs.menuitem'),
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
