# Generated by Django 5.1 on 2024-10-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0023_remove_packagemanagement_additional_day_price_and_more'),
        ('staffs', '0008_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='rooms',
            field=models.ManyToManyField(related_name='packages', to='staffs.room'),
        ),
    ]
