# Generated by Django 5.1 on 2024-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0026_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='activities',
            field=models.ManyToManyField(blank=True, to='adminpanal.activity'),
        ),
    ]
