# Generated by Django 5.1 on 2024-10-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0027_packagemanagement_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
