# Generated by Django 5.1 on 2024-10-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0028_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
