# Generated by Django 5.1 on 2024-10-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0030_packagemanagement_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='food_categories',
            field=models.ManyToManyField(blank=True, to='adminpanal.foodcategory'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanal.foodcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='adminpanal.menuitem'),
        ),
    ]
