# Generated by Django 5.1 on 2024-10-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0032_daycationpackage_packageaddon_daycationbooking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
