# Generated by Django 5.1 on 2024-10-17 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0034_daycationpackage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycationpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daycation_packages', to='adminpanal.category'),
        ),
    ]
