# Generated by Django 5.1 on 2024-10-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0035_daycationpackage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycationpackage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='packagefeature',
            name='description',
        ),
        migrations.AddField(
            model_name='daycationpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.AlterField(
            model_name='daycationpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='adminpanal.category'),
        ),
        migrations.DeleteModel(
            name='DaycationPackage1',
        ),
    ]
