# Generated by Django 5.1 on 2024-10-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0037_daycationpackage_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagefeature',
            options={'ordering': ['package', 'name'], 'verbose_name': 'Package Feature', 'verbose_name_plural': 'Package Features'},
        ),
    ]
