# Generated by Django 5.1 on 2024-10-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0040_daycationbooking_address_daycationbooking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycationbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='daycationpackage',
            name='available_capacity',
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='daycationpackage',
            name='max_capacity',
            field=models.IntegerField(),
        ),
    ]
