# Generated by Django 5.1 on 2024-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0041_remove_daycationbooking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycationbooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
