# Generated by Django 5.1 on 2024-10-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0042_daycationbooking_razorpay_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='daycationbooking',
            old_name='guests',
            new_name='num_adults',
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='food_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], default='non-veg', max_length=10),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
