# Generated by Django 5.1 on 2024-10-20 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0043_rename_guests_daycationbooking_num_adults_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daycationbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='adminpanal.packageaddon'),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanal.daycationpackage'),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daycation_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
