# Generated by Django 5.1 on 2024-10-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0044_alter_daycationbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycationbooking',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='daycationbooking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_applicable', max_length=20),
        ),
    ]
