# Generated by Django 5.1 on 2024-10-23 10:13

import adminpanal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0045_daycationbooking_cancellation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='daycationbooking',
            name='booking_reference',
            field=models.CharField(default=adminpanal.models.generate_booking_reference, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
