# Generated by Django 5.1 on 2024-10-26 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0047_alter_daycationbooking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='daycationpackage',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='daycation_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
