# Generated by Django 5.1 on 2024-11-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0049_remove_daycationpackage_wishlist_wishlist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycationpackage',
            name='wishlist_users',
            field=models.ManyToManyField(related_name='wishlisted_packages', through='adminpanal.Wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanal.daycationpackage'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
