# Generated by Django 5.1 on 2024-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0050_alter_daycationpackage_wishlist_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycationpackage',
            name='max_bookings',
            field=models.IntegerField(default=3),
        ),
    ]
