# Generated by Django 5.1 on 2024-11-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0051_daycationpackage_max_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycationbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
