# Generated by Django 5.1 on 2024-11-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0052_alter_daycationbooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycationbooking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='daycationbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
