# Generated by Django 5.1 on 2024-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintain', 'Maintain'), ('occupied', 'Occupied')], default='available', max_length=10),
        ),
    ]
