# Generated by Django 5.1 on 2024-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_foodcategory_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
