# Generated by Django 5.1 on 2024-10-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_room_description_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
