# Generated by Django 5.1 on 2024-10-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_room_available_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
