# Generated by Django 5.1 on 2025-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0014_alter_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageResort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('highlights', models.TextField(blank=True)),
                ('duration', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='packages/')),
            ],
        ),
    ]
