# Generated by Django 5.1 on 2025-01-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0015_packageresort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageResort',
        ),
    ]
