# Generated by Django 5.1 on 2024-09-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_fooditem_package_remove_booking_food_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.CharField(default='images/default.jpg', max_length=255),
        ),
    ]
