# Generated by Django 5.1 on 2024-10-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0013_packagemanagement_delete_package'),
        ('staffs', '0006_room_price'),
        ('userapp', '0003_rename_booking_bookingmanagement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingManagement',
            new_name='PackageBooking',
        ),
    ]
