# Generated by Django 5.1 on 2024-10-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_bookingmanagement_packagebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
