# Generated by Django 5.1 on 2024-09-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userdb_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='emailid',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='userdb',
            old_name='mobilenumber',
            new_name='mobile_number',
        ),
    ]
