# Generated by Django 5.1 on 2024-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_emailid_userdb_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
