# Generated by Django 5.1 on 2024-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_userdb_last_login_userdb_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
