# Generated by Django 5.1 on 2024-10-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_packagebooking_menu_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagebooking',
            old_name='num_adults',
            new_name='number_of_adults',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='package',
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='package_name',
            field=models.CharField(default='Default Package', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdb'),
        ),
    ]
