# Generated by Django 5.1 on 2024-09-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_userdb_last_login_alter_userdb_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
