# Generated by Django 5.1 on 2024-09-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
