# Generated by Django 5.1 on 2024-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_tbl_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_login',
        ),
        migrations.AddField(
            model_name='userdb',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
