# Generated by Django 5.1 on 2024-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_bookingpackage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackage',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
