# Generated by Django 5.1 on 2024-10-22 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_userdb_is_email_verified_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userdb',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userdb',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='userdb',
            table=None,
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='username',
        ),
    ]
