# Generated by Django 5.1 on 2024-10-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_rename_email_userdb_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='emailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
