# Generated by Django 5.1 on 2024-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_alter_userdb_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='emailid',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
