# Generated by Django 5.1 on 2024-10-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_remove_userdb_unique_email_phone_combination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='emailid',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterModelTable(
            name='userdb',
            table=None,
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='reset_token',
        ),
    ]
