# Generated by Django 5.1 on 2024-10-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_alter_userdb_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdb',
            table='users',
        ),
    ]
