# Generated by Django 5.1 on 2024-10-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_alter_userdb_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackage',
            name='food_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='num_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
