# Generated by Django 5.1 on 2024-10-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0032_bookingpackage_food_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpackage',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
