# Generated by Django 5.1 on 2024-10-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_remove_bookingpackage_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_applicable', max_length=20)),
            ],
        ),
    ]
