# Generated by Django 5.1 on 2024-10-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_daycationbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaycationBooking',
        ),
    ]
