# Generated by Django 5.1 on 2024-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0035_delete_daycationbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageBooking',
        ),
    ]
