# Generated by Django 5.1 on 2024-10-23 21:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_delete_packagebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='email',
            new_name='emailid',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='food_preference',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='num_rooms',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('upi', 'UPI')], default='credit_card', max_length=50),
        ),
        migrations.AddField(
            model_name='userdb',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobilenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be between 10 and 15 digits and can optionally start with a "+" sign.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together={('emailid', 'username')},
        ),
    ]
