# Generated by Django 5.1 on 2024-10-23 22:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userapp', '0038_alter_bookingpackage_payment_method_packagebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='emailid',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='food_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='num_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdb',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdb',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='userdb_set', related_query_name='userdb', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userdb_set', related_query_name='userdb', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18'), django.core.validators.MaxValueValidator(120, message='Age must be less than 120')]),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobilenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric or contain underscores', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='reset_token',
        ),
    ]
