# Generated by Django 5.1 on 2024-10-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0039_rename_emailid_userdb_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageBooking',
        ),
    ]
