# Generated by Django 5.1 on 2024-10-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0040_delete_packagebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
