# Generated by Django 5.1 on 2024-10-23 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0042_rename_email_userdb_emailid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
