# Generated by Django 5.1 on 2025-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0043_userdb_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('resort_owner', 'Resort Owner')], default='customer', max_length=50),
        ),
        migrations.AddField(
            model_name='userdb',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
