# Generated by Django 5.1 on 2025-01-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0044_userdb_account_type_userdb_email_userdb_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
