# Generated by Django 5.1 on 2025-02-01 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0045_remove_userdb_account_type_remove_userdb_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userdb',
            old_name='emailid',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together={('email', 'username')},
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='bookingpackage',
            name='room',
        ),
        migrations.AddField(
            model_name='userdb',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobilenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Mobile number must be between 10 and 15 digits and can optionally start with a '+' sign.", regex='^\\+?\\d{10,15}$')]),
        ),
    ]
