# Generated by Django 5.1 on 2024-10-11 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0009_alter_packagebooking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='Default Package', max_length=100)),
                ('number_of_adults', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('cash', 'Cash')], max_length=50)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_entries', to='userapp.userdb')),
            ],
            options={
                'db_table': 'booking_entries',
                'ordering': ['-booking_date'],
            },
        ),
    ]
