# Generated by Django 5.1 on 2024-10-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
    ]
