# Generated by Django 5.1 on 2024-10-22 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_package_name_and_more'),
        ('userapp', '0028_rename_emailid_userdb_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_entries', to='userapp.userdb'),
        ),
    ]
