# Generated by Django 5.1 on 2025-02-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
